steal.loading('components/user/static_comp/static_comp.js','components/user/static_comp/controllers/static_comp_controller.js','components/user/static_comp/models/static_comp_model.js','components/user/static_comp/views/index.tmpl');
steal({src: 'components/user/static_comp/production/production.css', has: ['resources/plugins/jquery-filetype/jquery-filetype.css']});
steal.options.env=="development"?steal(function(){steal.isRhino!==undefined&&steal({src:"components/user/core/production",packaged:false})}).then("//resources/plugins/jquery-filetype/jquery-filetype.css","./controllers/static_comp_controller.js","./models/static_comp_model.js","./views/index.tmpl",{src:"jquery",packaged:false},{src:"jquery/view",packaged:false},{src:"jquery/view/tmpl",packaged:false}):steal("components/user/static_comp/production/production.css").then("components/user/static_comp/production/production.js");
steal.loaded("components/user/static_comp/static_comp.js");
$.Controller.extend("Static_comp",{defaults:{viewpath:"//components/user/static_comp/views/",pref:"ru"}},{init:function(e,f,d,b,a){var g=this;e={static_component_id:f,menu_item_id:d};this.Class.defaults.pref=chose_lang_pref_by_lang_id(a);this.Class.container=$("."+this.Class.fullName.toLowerCase());this.window=this.Class.container.parents(".window-container");this.main=b;f=f+"/"+d+"/"+b+"/"+a;$('div.window-container[data-false_window="staticcomp"]').length?this.success_get_menu_content(false):Static_comp_model.get_menu_item_content(e,
f,function(h){g.success_get_menu_content(h)},g.error)},success_get_menu_content:function(e){var f=this.Class.container.parents(".window-container").attr("id"),d="",b="";if(e!==false){d=e.data.menu_item.lang[this.Class.defaults.pref].value;e.data.lang[this.Class.defaults.pref]&&this.Class.container.parents(".window-container").data("state")!=="minimized"&&Windows.setHeadTitle(e.data.lang[this.Class.defaults.pref].seo_title);b=$.View(this.Class.defaults.viewpath+"index.tmpl",{our_data:e.data,site_url:base_url,
pref:this.Class.defaults.pref})}else this.main=1;windowCallBack(e,f,d,b,"staticcomp",this.main)},error:function(){alert("Sorry for the technical work carried out online")}});steal.loaded("components/user/static_comp/controllers/static_comp_controller.js");$.Model.extend("Static_comp_model",{get_menu_item_content:function(e,f,d,b){$.ajax({url:base_url+"user_controller/get_static_component/"+f,type:"post",data:e,dataType:"json",success:this.callback(d),error:b})}},{});steal.loaded("components/user/static_comp/models/static_comp_model.js");
steal("jquery/view/tmpl").then(function(e){e.View.preload("components_user_static_comp_views_index_tmpl",function(f){return function(d,b){var a=[],g=b.data;with(g){a.push('<div class="seo_title" style="display: none;">');if(typeof our_data.lang[pref].seo_title!=="undefined"&&our_data.lang[pref].seo_title!=null)a.push(d.encode(typeof our_data.lang[pref].seo_title==="function"?our_data.lang[pref].seo_title.call(b):our_data.lang[pref].seo_title));a.push('</div> <div class="article_wrapper">     ');if(typeof(our_data.lang&&
our_data.lang[pref])!=="undefined"&&(our_data.lang&&our_data.lang[pref])!=null&&(typeof(our_data.lang&&our_data.lang[pref])==="function"?(our_data.lang&&our_data.lang[pref]).call(b):our_data.lang&&our_data.lang[pref])){a.push("         <img src='");if(typeof site_url!=="undefined"&&site_url!=null)a.push(d.encode(typeof site_url==="function"?site_url.call(b):site_url));a.push("images/wind_top_bg.jpg' class='article_top_bg'>         <img src='");if(typeof site_url!=="undefined"&&site_url!=null)a.push(d.encode(typeof site_url===
"function"?site_url.call(b):site_url));a.push("images/wind_left3.jpg' class='article_left3'>         <h1 class=\"article_caption\" data-menu_id=\"");if(typeof id!=="undefined"&&id!=null)a.push(d.encode(typeof id==="function"?id.call(b):id));a.push('">');if(typeof our_data.lang[pref].title!=="undefined"&&our_data.lang[pref].title!=null)a.push(d.encode(typeof our_data.lang[pref].title==="function"?our_data.lang[pref].title.call(b):our_data.lang[pref].title));a.push('</h1>         <div class="article_date" data-menu_id="');
if(typeof id!=="undefined"&&id!=null)a.push(d.encode(typeof id==="function"?id.call(b):id));a.push('">');if(typeof our_data.date!=="undefined"&&our_data.date!=null)a.push(d.encode(typeof our_data.date==="function"?our_data.date.call(b):our_data.date));a.push('</div>         <div class="clear"></div>         <div class="article_content_wrapper" data-menu_id="');if(typeof id!=="undefined"&&id!=null)a.push(d.encode(typeof id==="function"?id.call(b):id));a.push('">');if(typeof our_data.lang[pref].description!==
"undefined"&&our_data.lang[pref].description!=null&&(typeof our_data.lang[pref].description==="function"?our_data.lang[pref].description.call(b):our_data.lang[pref].description)){a.push("");if(typeof our_data.lang[pref].description!=="undefined"&&our_data.lang[pref].description!=null)a.push(typeof our_data.lang[pref].description==="function"?our_data.lang[pref].description.call(b):our_data.lang[pref].description);a.push("")}a.push('</div>         <div class="article_files_wrapper" data-menu_id="');
if(typeof id!=="undefined"&&id!=null)a.push(d.encode(typeof id==="function"?id.call(b):id));a.push('">             ');if(typeof our_data.file!=="undefined"&&our_data.file!=null&&(typeof our_data.file==="function"?our_data.file.call(b):our_data.file)){a.push("                 ");if(typeof our_data.file!=="undefined"&&our_data.file!=null)d.each(typeof our_data.file==="function"?our_data.file.call(b):our_data.file,function(h,c){with(this){a.push('                     <a target="_blank" href="');if(typeof site_url!==
"undefined"&&site_url!=null)a.push(d.encode(typeof site_url==="function"?site_url.call(b):site_url));a.push("");if(typeof c.directory!=="undefined"&&c.directory!=null)a.push(d.encode(typeof c.directory==="function"?c.directory.call(b):c.directory));a.push("/");if(typeof c.name!=="undefined"&&c.name!=null)a.push(d.encode(typeof c.name==="function"?c.name.call(b):c.name));a.push('" title="');if(typeof c.short_description!=="undefined"&&c.short_description!=null)a.push(d.encode(typeof c.short_description===
"function"?c.short_description.call(b):c.short_description));a.push('" class="');if(typeof c.type!=="undefined"&&c.type!=null)a.push(d.encode(typeof c.type==="function"?c.type.call(b):c.type));a.push('">                         <span class="file-icon"></span>                         <span class="file-text">');if(typeof c.short_description!=="undefined"&&c.short_description!=null)a.push(d.encode(typeof c.short_description==="function"?c.short_description.call(b):c.short_description));a.push(".");if(typeof c.type!==
"undefined"&&c.type!=null)a.push(d.encode(typeof c.type==="function"?c.type.call(b):c.type));a.push("</span>                     </a>                 ")}});a.push("             ")}a.push("         </div>     ")}a.push('     <div class="trilan_links">         <div class="brs">');if(typeof our_data.trilan.brs!=="undefined"&&our_data.trilan.brs!=null)a.push(typeof our_data.trilan.brs==="function"?our_data.trilan.brs.call(b):our_data.trilan.brs);a.push('</div>         <div class="cpr" style="margin-top: 10px;">');
if(typeof our_data.trilan.cpr!=="undefined"&&our_data.trilan.cpr!=null)a.push(typeof our_data.trilan.cpr==="function"?our_data.trilan.cpr.call(b):our_data.trilan.cpr);a.push("</div>     </div> </div>")}return a}.call(jQuery,jQuery,{data:f}).join("")})});steal.loaded("components/user/static_comp/views/index.tmpl");
