steal.loading('components/user/paginator/paginator.js','components/user/paginator/controllers/paginator_controller.js','components/user/paginator/models/paginator_model.js','components/user/paginator/views/paginator.tmpl');
steal({src: 'components/user/paginator/production/production.css', has: ['components/user/paginator/css/paginator.css']});
steal.options.env=="development"?steal(function(){steal.isRhino!==undefined&&steal({src:"components/user/core/production",packaged:false})}).then("./css/paginator.css","./controllers/paginator_controller","./models/paginator_model","./views/paginator.tmpl",{src:"jquery",packaged:false},{src:"jquery/view",packaged:false},{src:"jquery/view/tmpl",packaged:false}):steal("components/user/paginator/production/production.css","components/user/paginator/production/production.js");steal.loaded("components/user/paginator/paginator.js");
$.Controller.extend("Paginator",{defaults:{viewpath:"//components/user/paginator/views/"}},{init:function(a,d){$(a).append('<div class="paginate"></div>');this.paginate_wrap=$(a).find(".paginate");this.opt=$.extend({items:1,itemsOnPage:1,pages:0,displayedPages:3,edges:1,currentPage:1,hrefTextPrefix:"",hrefTextSuffix:"",prevText:'<img src="'+base_url+'images/pagin_prev.jpg">',nextText:'<img src="'+base_url+'images/pagin_next.jpg">',ellipseText:"&hellip;",cssStyle:"light-theme",selectOnClick:true,request:"",
pageSelector:"",viewpath:"",viewData:"",onPageClick:function(){},onInit:function(){}},d||{});this.opt.pages=this.opt.pages?this.opt.pages:Math.ceil(this.opt.items/this.opt.itemsOnPage)?Math.ceil(this.opt.items/this.opt.itemsOnPage):1;this.opt.currentPage-=1;this.opt.halfDisplayed=this.opt.displayedPages/2;this.opt.pages>1&&this._draw();this.opt.onInit()},_draw:function(){var a=this.opt,d=this._getInterval(),b;this.paginate_wrap.empty();a.prevText&&this._appendItem(a.currentPage-1,{text:a.prevText,
classes:"prev"});if(d.start>0&&a.edges>0){var f=Math.min(a.edges,d.start);for(b=0;b<f;b++)this._appendItem(b);a.edges<d.start&&a.ellipseText&&this.paginate_wrap.append('<span class="ellipse">'+a.ellipseText+"</span>")}for(b=d.start;b<d.end;b++)this._appendItem(b);if(d.end<a.pages&&a.edges>0){a.pages-a.edges>d.end&&a.ellipseText&&this.paginate_wrap.append('<span class="ellipse">'+a.ellipseText+"</span>");for(b=Math.max(a.pages-a.edges,d.end);b<a.pages;b++)this._appendItem(b)}a.nextText&&this._appendItem(a.currentPage+
1,{text:a.nextText,classes:"next"})},_getInterval:function(){return{start:Math.ceil(this.opt.currentPage>this.opt.halfDisplayed?Math.max(Math.min(this.opt.currentPage-this.opt.halfDisplayed,this.opt.pages-this.opt.displayedPages),0):0),end:Math.ceil(this.opt.currentPage>this.opt.halfDisplayed?Math.min(this.opt.currentPage+this.opt.halfDisplayed,this.opt.pages):Math.min(this.opt.displayedPages,this.opt.pages))}},_appendItem:function(a,d){var b;b=this.opt;a=a<0?0:a<b.pages?a:b.pages-1;d=$.extend({text:a+
1,classes:""},d||{});b=a==b.currentPage||b.disabled?$('<span class="current">'+d.text+"</span>"):$('<a href="'+b.hrefTextPrefix+(a+1)+b.hrefTextSuffix+'" class="page-link">'+d.text+"</a>");d.classes&&b.addClass(d.classes);this.opt.pages-1==a&&b.addClass("last");this.paginate_wrap.append(b)},".page-link click":function(a,d){d.preventDefault();this._selectPage($(a).attr("href")-1)},_selectPage:function(a){this.opt.currentPage=a;if(this.opt.selectOnClick){Paginator_model.getData(this.opt.request+"/"+
this.opt.itemsOnPage+"/"+a*this.opt.itemsOnPage,this.callback("dataGeted"),this.callback("error"));this.opt.onPageClick(a+1);this._draw()}else this.opt.onPageClick(a+1)},dataGeted:function(a){a=$.View(this.opt.viewpath,{our_data:a.data.data,site_url:base_url,pref:chose_lang_pref_by_lang_id(parseInt($.cookie("lang"))),lang_id:$.cookie("lang"),viewdata:this.opt.viewData});$(this.opt.pageSelector).html(a)},error:function(){alert("Unknown error")}});steal.loaded("components/user/paginator/controllers/paginator_controller.js");
$.Model("Paginator_model",{getData:function(a,d,b){$.ajax({url:a,type:"post",dataType:"json",data:{},success:this.callback(d),cache:false,error:this.callback(b)})}},{});steal.loaded("components/user/paginator/models/paginator_model.js");
steal("jquery/view/tmpl").then(function(a){a.View.preload("components_user_paginator_views_paginator_tmpl",function(d){return function(b,f){var e=[],h=f.data;with(h){e.push('<div class="paginate">     ');if(typeof our_data.length!=="undefined"&&our_data.length!=null&&(typeof our_data.length==="function"?our_data.length.call(f):our_data.length)){e.push('         <a class="paginate_prev">             <img src=\'');if(typeof site_url!=="undefined"&&site_url!=null)e.push(b.encode(typeof site_url==="function"?
site_url.call(f):site_url));e.push("images/pagin_prev.jpg'>         </a>         <span>             ");if(typeof our_data!=="undefined"&&our_data!=null)b.each(typeof our_data==="function"?our_data.call(f):our_data,function(c,g){with(this){e.push('                 <a href="');if(typeof g!=="undefined"&&g!=null)e.push(b.encode(typeof g==="function"?g.call(f):g));e.push('" class="paginate_item');if(typeof(c==0)!=="undefined"&&c==0!=null&&(typeof(c==0)==="function"?(c==0).call(f):c==0))e.push(" paginate_active");
e.push("");if(typeof(c+1>=show_numbers&&c+1!==our_data.length)!=="undefined"&&(c+1>=show_numbers&&c+1!==our_data.length)!=null&&(typeof(c+1>=show_numbers&&c+1!==our_data.length)==="function"?(c+1>=show_numbers&&c+1!==our_data.length).call(f):c+1>=show_numbers&&c+1!==our_data.length))e.push(" hidden");else{e.push("");if(typeof(c+2==show_numbers)!=="undefined"&&c+2==show_numbers!=null&&(typeof(c+2==show_numbers)==="function"?(c+2==show_numbers).call(f):c+2==show_numbers))e.push(" last");e.push("")}e.push('" >                     ');
if(typeof(c+1)!=="undefined"&&c+1!=null)e.push(b.encode(typeof(c+1)==="function"?(c+1).call(f):c+1));e.push("                 </a>                 ");if(typeof(c+2==show_numbers)!=="undefined"&&c+2==show_numbers!=null&&(typeof(c+2==show_numbers)==="function"?(c+2==show_numbers).call(f):c+2==show_numbers))e.push("                     <span>...</span>                 ");e.push("             ")}});e.push('         </span>         <a class="paginate_next">             <img src=\'');if(typeof site_url!==
"undefined"&&site_url!=null)e.push(b.encode(typeof site_url==="function"?site_url.call(f):site_url));e.push("images/pagin_next.jpg'>         </a>     ")}e.push(" </div>")}return e}.call(jQuery,jQuery,{data:d}).join("")})});steal.loaded("components/user/paginator/views/paginator.tmpl");
